[project]
name = "Geti-demo"
version = "1.0.0"
description = "A minimal demo showcasing how to run inference with a model exported from Geti using OpenVINO Model API."
requires-python = ">=3.13,<3.14"

dependencies = [
    "openvino~=2026.3.0",
    "openvino-model-api[onnx]==0.4.6",
    "opencv-python-headless~=4.13.0",
    "numpy>=2.0",
    "pillow~=12.0",
]
