apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: retriever-milvus
  name: retriever-milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: retriever-milvus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: retriever-milvus
    spec:
      containers:
        - env:
            - name: DEVICE
              value: GPU.1
            - name: HF_ENDPOINT
              value: https://hf-mirror.com
            - name: LOCAL_EMBED_MODEL_ID
              value: CLIP-ViT-H-14
            - name: MILVUS_HOST
              value: 10.67.108.247
            - name: MILVUS_PORT
              value: "19530"
            - name: MODEL_DIR
              value: /home/user/models
            - name: http_proxy
              value: http://child-prc.intel.com:913
            - name: https_proxy
              value: http://child-prc.intel.com:913
            - name: no_proxy
              value: localhost,127.0.0.1,::1,192.168.49.2
          image: retriever-milvus:latest
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:7770/v1/retrieval/health || exit 1
            failureThreshold: 30
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          name: retriever-milvus
          ports:
            - containerPort: 7770
              protocol: TCP
      restartPolicy: Always
      securityContext:
        supplementalGroups:
          - 1000
          - 44
          - 992
