apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: retriever-milvus
  name: retriever-milvus
spec:
  ports:
    - name: "7770"
      port: 7770
      targetPort: 7770
  selector:
    io.kompose.service: retriever-milvus
