apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: visual-search-qa-app
  name: visual-search-qa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: visual-search-qa-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: visual-search-qa-app
    spec:
      containers:
        - env:
            - name: BACKEND_DATAPREP_BASE_URL
              value: http://10.67.108.247:9990
            - name: BACKEND_SEARCH_BASE_URL
              value: http://10.67.108.247:7770
            - name: BACKEND_VQA_BASE_URL
              value: http://10.67.108.247:8399
            - name: HOST_DATA_PATH
              value: /home/user/data
            - name: LOCAL_EMBED_MODEL_ID
              value: CLIP-ViT-H-14
            - name: TEMP_VIDEO_CONTAINER_ROOT
              value: /home/user/data/tmp
            - name: TEMP_VIDEO_HOST_ROOT
              value: /tmp
            - name: http_proxy
              value: http://child-prc.intel.com:913
            - name: https_proxy
              value: http://child-prc.intel.com:913
            - name: no_proxy
              value: localhost,127.0.0.1,::1,192.168.49.2
          image: visual-search-qa-app:latest
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - echo 'Health check' || exit 1
            failureThreshold: 30
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          name: visual-search-qa-app
          ports:
            - containerPort: 17580
              protocol: TCP
      restartPolicy: Always
